# ===========================================
# Site Information Settings
# ===========================================
# 站点根目录，默认为 /，如果没有部署到根目录，请修改
site_root: /
# 是否允许用户复制网站上的内容，仅仅是君子协定
selectable: true

# 文字是否缩进（2字符）
text_indent: true

# Dark mode
# Available values: true, false, auto
dark_mode: auto

# Round corner
# Warning: This feature is NOT fully tested on various browsers.
smooth_corner: false

# Code settings
code:
  # Force hide line numbers
  line_number: false

# Counting words
word_count:
  enable: true
  mode: all # or en_only | zh_only
  reading_time: false
  reading_speed:
    cn: 300
    en: 160

# Site creation time
since_year: 2018

# search
# hexo-generator-search
# Please see https://github.com/wzpan/hexo-generator-search/tree/master for detail.
search:
  enable: false
  path: meta.json # changeable
  field: post
  content: false # currently unsupported


# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives:
    widget: Archives
#  Posts:
#    name: posts # category name
#    widget: Posts
  Tags:
    widget: Tags

# key: link text, value: URL link
header_menu:
  About: /about

# 文章右侧TOC导航
# 对于每篇文章，都可以使用"toc: false|true"指定是否显示toc
# 不设置则默认与下面的toc.enable保持一致
toc:
  enable: true
  list_number: true  # 是否显示数字排序

# A sentence to show
signature: 热爱生活，然后发现，处处都是阳光

comment:
  enable: false
  type: 'valine'
  valine:
    placeholder: 'Just go go.'
    app_id:
    app_key:
  twikoo:
    envID:

excerpt_link: 更多

# 版权信息
post_copy:
  text: 署名-非商业性使用-相同方式共享
  text_en: CC BY-NC-SA 4.0
  link: https://creativecommons.org/licenses/by-nc/4.0/

# 自定义页脚
footer_links:
custom_footer:

# 备案
beian:
  enable: false
  icp:

# 统计
visit_count:
  type: busuanzi
  # or
  # type: visitor-counter
  # url: //your.counter.site/count.php

umami:
  enable: false
  url:
  website_id:

# 辅助样式，默认开启
helpers: true

favicon: /img/favicon.ico
